Fixed a Chat Bug With Standard Simba Installs
Fixed an error for standard Simbas which was caused by doing similar to
the following:
someStringArray+='';

Which would result in:
Error: Can't assign "AnsiString" to "array of AnsiString" at line 165